apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-web-page
  namespace: helm
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"  

spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: {{.Release.Name}}-web-page
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-web-page
    spec:
      containers:
        - name: web-page
          image: {{ .Values.application.image.name }}:{{ .Values.application.image.tag }}   
          ports:
            - containerPort: 80