{{if .Values.application.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress
  namespace: helm

spec:
  ingressClassName: nginx

  rules:
    - host: web-page.localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{.Release.Name}}-svc
                port:
                  number: 7900
{{end}}