apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  namespace: helm

spec:
  selector:
    app: {{.Release.Name}}-web-page
  ports:
    - port: {{.Values.application.port}}
      targetPort: 80
  type: {{.Values.application.service.type}}  