apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc

spec:
  selector:
    app: {{.Release.Name}}-web-page
  ports:
    - port: 80
      targetPort: 80
  type: {{.Values.application.service.type}}  
  
  