apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  namespace: helm

spec:
  selector:
    app: {{.Release.Name}}-web-page
  ports:
    - port: 8081
      targetPort: 8081
  type: {{.Values.application.service.type}}  
  
  